config/routes.rb
Rails.application.routes.draw do
  
  get 'users/new'

  get 'orderitems/index'

  get 'orderitems/shpw'

  get 'orderitems/new'

  get 'orderitems/edit'
  

  devise_for :users do
    resources :orders
  end
  
  resources :orders do
    resources :orderitems
  end
  
  get "cart/index"

  get "site/about"
  get "site/contact"
  get "site/home"
  get "site/portfolio"
  get "site/newborn_gallery"
  get "site/children_gallery"
  get "site/maternity_gallery"
  

  resources :items
  
  get '/cart' => 'cart#index'
  get '/cart/:id' => 'cart#add'
  get '/cart/remove/:id' => 'cart#remove'
  get '/clearCart' => 'cart#clearCart'
  get '/checkout' => 'cart#createOrder'
  
  get '/about' => 'site#about'
  get '/contact' => 'site#contact'
  get '/home' => 'site#home'
  get '/portfolio' => 'site#portfolio'
  get '/newborn_gallery' => 'site#newborn_gallery'
  get '/children_gallery' => 'site#children_gallery'
  get '/maternity_gallery' => 'site#maternity_gallery'

  get '/signup' => 'users#new'
  resources :users
  
  root :to => 'site#home'

 
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  
 attr_accessible :order_date, :user_id
 
 has_many :orderitems
 
 belongs_to :user
 
end

app/models/orderitem.rb
class Orderitem < ActiveRecord::Base
  belongs_to :order
end

app/models/user.rb
class User < ActiveRecord::Base
 # Include default devise modules. Others available are:
 # :token_authenticatable, :confirmable,
 # :lockable, :timeoutable and :omniauthable
 devise :database_authenticatable, :registerable,
 :recoverable, :rememberable, :trackable, :validatable
 # Setup accessible (or protected) attributes for your model
 #attr_accessible :email, :password, :password_confirmation, :remember_me
 
 has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def add
    id = params[:id]
    
    cart = session[:cart] ||= {}
    cart[id] = (cart[id] || 0) + 1
    
    redirect_to :action => :index
  end
  
  def index
    @cart = session[:cart] || {}
  end
  
  def change
    cart = session[:cart]
    id = params[:id];
    quantity = params[:quantity].to_i
  if cart and cart[id]
    unless quantity <= 0
      cart[id] = quantity
    else
      cart.delete id
    end
  end
  redirect_to :action => :index
  end
  
  def remove
    id = params[:id]
    cart = session[:cart]
    cart.delete id

    redirect_to :action => :index   
  end
  
  def checkout
    flash[:notice] = "CHECKOUT IS NOT IMPLEMENTED YET!!!"
    
    redirect_to :action => :index
  end
  
  def clearCart
    session[:cart] = nil
    redirect_to :action => :index
  end
  
  def createOrder
    # Step 1: Get the current user
    @user = User.find(current_user.id)
  
    # Step 2: Create a new order and associate it with the current user
    @order = @user.orders.build(:OrderDate => DateTime.now)
    @order.save
  
    # Step 3: For each item in the cart, create a new item on the order!!
    @cart = session[:cart] || {} # Get the content of the Cart
    @cart.each do | id, quantity |
     item = Item.find_by_id(id)
     @orderitem = @order.orderitems.build(:item_id => item.id, :title => item.title, :description => item.description, :quantity => quantity, :price => item.price)
    @orderitem.save
  end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url, :category)
    end
end

app/controllers/orderitems_controller.rb
class OrderitemsController < ApplicationController
  def index
  end

  def shpw
  end

  def new
  end

  def edit
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:OrderDate, :user_id)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def about
  end

  def contact
  end

  def home
  end

  def portfolio
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
       flash[:success] = "Welcome to BAM Photographers website!"
       redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orderitems_helper.rb
module OrderitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.email, class: "gravatar")
  end
end

app/views/User/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/cart/index.html.erb
<h1>Your Cart</h1>
<% if @cart.empty? %>
 <p>Your Cart is empty.</p>
<% end %>
<% total = 0 %>
<table class="cart">
 <tr>
 <td class="legend"></td>
 <td class="legend">Item</td>
 <td class="legend">Price</td>
 <td class="legend">Qty</td>
 <td class="legend">Total</td>
 </tr>
<% @cart.each do | id, quantity | %>
 <% item = Item.find_by_id(id) %>
 <tr>
 <td>
 <div class="image">
 <%= link_to (image_tag item.image_url, :style => "height:40px"), item %>
 </div>
 </td>
 <td class="title"><%= link_to item.title, item %></td>
 <td class="price"><%= number_to_currency(item.price) %></td>
 <td class="quantity"><%= quantity %><br /></td>
 <td class="price">
 <%= number_to_currency(quantity * item.price, :unit => "£") %>
 </td>
 <td><a href="/cart/remove/<%= item.id %>">Remove from Cart</a></td>
 </tr>
 <% total += quantity * item.price %>
<% end %>
 <tr>
 <td colspan="4">
 <div class="total">Total:</div>
 </td>
 <td>
 <div class="price"><%= number_to_currency(total, :unit => "€") %></div>
 </td>
 </tr>
 </table>
<p>
 <%= link_to 'Continue Shopping', :controller => :items %>
</p>
<%= link_to 'Clear Cart', :controller => "cart", :action => "clearCart" %>
<%= link_to 'Check Out', :controller => "cart", :action => "createOrder" %>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>BAM Photographers</title>
    <link rel="stylesheet" href="css/normalize.css">
    <link href='https://fonts.googleapis.com/css?family=Montserrat|Ubuntu:400,400italic,700|Titillium+Web:400,400italic,700|Open+Sans:400,400italic,700,800' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="css/main.css">
    <link rel="stylesheet" href="css/responsive.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <header>
      <a href="index.html" id="logo">
        <img src="assets/BAM_logogrey.png" alt="mainpicture">
      </a>
    </header>
    
      <nav class="center">
        <ul>
          <li><a href="home.html" class="selected">Home</a></li>
          <li><a href="portfolio.html">Portfolio</a></li>
		      <li><a href="about.html">About</a></li>
          <li><a href="contact.html">Contact</a></li>
        </ul>
      </nav>


<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>



<div id="wrapper">
     
       <div class="footerinfo">
          <li><p id="tooltip1"><a href="/site/about.html">About Us<span>We specialize in newborn & children photography, maternity and family photo sesion is also within our area of expertise.</span></a></p></li>
          <li><p id="tooltip1"><a href="https://www.google.com/maps/place/National+College+of+Ireland,+Mayor+Street+Lower,+International+Financial+Services+Centre,+Dublin+1,+Ireland/@53.348729,-6.243568,15z/data=!4m2!3m1!1s0x48670e8d1bdaf2ed:0x20fe35903d91c026?hl=en">Location<span>We are located at the National College of Ireland in Dublin.</span></a></p></li>
          <li><p id="tooltip1"><a href="/site/about.html">Contact Us<span>Send us an email</span></a></p></li>
       </div>
    	<br><br>
    	
      <footer>
        <a href="https://www.twitter.com/mmbcc"><img src="/assets/bampict/twitter-wrap.png" alt="Twitter Logo" class="social-icon"></a>
        <a href="https://www.facebook.com/maria.kohlmann2"><img src="/assets/bampict/facebook-wrap.png" alt="Facebook Logo" class="social-icon"></a>
        <div class="copyrights">&copy; 2016 BAM Photographers</div>
      </footer>
    </div>
    
</body>
</html>

app/views/items/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>BAM Photographers</title>
    <link rel="stylesheet" href="css/normalize.css">
    <link href='https://fonts.googleapis.com/css?family=Montserrat|Ubuntu:400,400italic,700|Titillium+Web:400,400italic,700|Open+Sans:400,400italic,700,800' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="css/main.css">
    <link rel="stylesheet" href="css/responsive.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
  
<h1>Catalog</h1>
<table class="catalog">
<% @items.each do |item| %>
 <tr>
 <td>
 <div class="image">
 <%= link_to (image_tag item.image_url, :style => "height:100px"), item %>
 </div>
 </td>
 <td>
 <div class="title">
 <%= link_to item.title, item %>
 </div>
 <div class="description">
 <%=h item.description %>
 </div>
 <div class="price">
 <%= number_to_currency(item.price, :unit => "&pound;") %>
 </div>
 <div class="links">
 <%= link_to 'Edit', edit_item_path(item) %> |
 <%= link_to 'Destroy', item, :confirm => 'Are you sure?', :method => :delete %>
 <a href="/cart/<%= item.id %>">Add to Cart</a><br><br>
 </div>

 </td>
 </tr>
<% end %>
</table>
<p><%= link_to 'New item', new_item_path %></p>


</body>
</html>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @item.image_url %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BAM Photographers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

    <meta charset="utf-8">
    <link rel="stylesheet" href="css/normalize.css">
    <link href='https://fonts.googleapis.com/css?family=Montserrat|Ubuntu:400,400italic,700|Titillium+Web:400,400italic,700|Open+Sans:400,400italic,700,800' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="css/main.css">
    <link rel="stylesheet" href="css/responsive.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <header>
      <a href="index.html" id="logo">
        <img src="/assets/BAM_logogrey.png" alt="mainpicture">
      </a>
    </header>
    
      <nav class="center">
        <ul>
          <li><a href="home.html">Home</a></li>
          <li><a href="portfolio.html">Portfolio</a></li>
		      <li><a href="about.html">About</a></li>
          <li><a href="contact.html">Contact</a></li>
         
<% if user_signed_in? %>
<div class="signin">Signed in as... <%= current_user.email %> (<%= link_to 'Sign out', destroy_user_session_path, :method => :delete%>)</div>
<% else %>
<%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary" %> or <%= link_to 'Sign in', new_user_session_path %>
<% end %>
        </ul>
      </nav>
      
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>


   <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
   <% end %>

<%= yield %>

<br><br>

     <footer>

      <%= debug(params) if Rails.env.development? %>

        <a  target="_blank" href="https://www.twitter.com/corroonb"><img src="/assets/twitter-wrap.png" alt="Twitter Logo" class="social-icon"></a>
        <a  target="_blank" href="https://www.facebook.com/MonikaZborowskaPhotography"><img src="/assets/facebook-wrap.png" alt="Facebook Logo" class="social-icon"></a>
        <div class="copyrights">&copy; 2016 BAM Photographers</div>
      </footer>

</body>
</html>

app/views/orderitems/edit.html.erb
<h1>Orderitems#edit</h1>
<p>Find me in app/views/orderitems/edit.html.erb</p>

app/views/orderitems/index.html.erb
<h1>Orderitems#index</h1>
<p>Find me in app/views/orderitems/index.html.erb</p>

app/views/orderitems/new.html.erb
<h1>Orderitems#new</h1>
<p>Find me in app/views/orderitems/new.html.erb</p>

app/views/orderitems/shpw.html.erb
<h1>Orderitems#shpw</h1>
<p>Find me in app/views/orderitems/shpw.html.erb</p>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :OrderDate %><br>
    <%= f.datetime_select :OrderDate %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th>Orderdate</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.OrderDate %></td>
        <td><%= order.user %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Orderdate:</strong>
  <%= @order.OrderDate %>
</p>

<p>
  <strong>User:</strong>
  <%= @order.user %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/site/about.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>BAM Photographers</title>
    <link rel="stylesheet" href="css/normalize.css">
    <link href='https://fonts.googleapis.com/css?family=Montserrat|Ubuntu:400,400italic,700|Titillium+Web:400,400italic,700|Open+Sans:400,400italic,700,800' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="css/main.css">
    <link rel="stylesheet" href="css/responsive.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>

      <div class="about">
         <img src="/assets/newborn/DSC_2901.jpg" alt="Photo of us" class="profile-photo">
        
          <p2>Hi, we are the BAM Photographers specialising in the Newborn & Children Photography and for real this is our Web Design project and this text is here to fill up the About Us page only. Hi, we are the BAM Photographers specialising in the Newborn & Children Photography and for real this is our Web Design project and this text is here to fill up the About Us page only.<br>
          <br>Our aim for you is to capture the love and the bond that you have for your little (and not so little) ones. We want to help tell your story of love. We’re all in so much of a rush these days that we rarely get time to just be with the ones we love. There’s always some distraction, some worry, the feeling that there’s something else we should be doing. For a couple of hours we want you to relax, have fun and spend time with the ones you love. We’ll be there to document this very special time and to create art that will remind you forever of how much you love one another.</p2> 
          <br><br>
          <p2>If you'd like to follow us on Flickr, click here <a href="https://www.flickr.com/photos/87122581@N06/"><p1>Flickr Gallery</p1></a></p2>
          <br><br>
          <p3>`Enjoy the little things, for one day you may look back and realise they were the big things` -Robert Brault</p3>
      
       </div>

  </body>
</html>

app/views/site/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>BAM Photographers</title>
    <link rel="stylesheet" href="css/normalize.css">
    <link href='https://fonts.googleapis.com/css?family=Montserrat|Ubuntu:400,400italic,700|Titillium+Web:400,400italic,700|Open+Sans:400,400italic,700,800' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="css/main.css">
    <link rel="stylesheet" href="css/responsive.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
   
    
    <div id="wrapper">
     <section>
	  
		<div class="mainimage">
			<a href="/assets/newborn/DSC_1071.jpg">
			<img src="/assets/newborn/DSC_1071.jpg" alt="mainpicture">
			</a>
		</div>
	          
      </section>
      
      
       <div class="footerinfo">
          <li><p id="tooltip1"><a href="about.html">About Us<span>We specialize in newborn & children photography, maternity and family photo sesion is also within our area of expertise.</span></a></p></li>
          <li><p id="tooltip1"><a href="https://www.google.com/maps/place/National+College+of+Ireland,+Mayor+Street+Lower,+International+Financial+Services+Centre,+Dublin+1,+Ireland/@53.348729,-6.243568,15z/data=!4m2!3m1!1s0x48670e8d1bdaf2ed:0x20fe35903d91c026?hl=en">Location<span>We are located at the National College of Ireland in Dublin.</span></a></p></li>
          <li><p id="tooltip1"><a href="contact.html">Contact Us<span>Send us an email</span></a></p></li>
       </div>
    	<br>
    	
     </div>
  </body>
</html>

app/views/users/new.html.erb
<div class="signup">

  <% provide(:title, 'Sign up') %>
  <h1>Sign up</h1>
  
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>  
      
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
  
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
  
        <%= f.submit "Create my account", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

</div>

app/views/users/show.html.erb
<% provide(:title, @user.email) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.email %>
      </h1>
    </section>
  </aside>
</div>